// !!! This is a file automatically generated by hipify!!!
// Copyright (c) 2009-2022, NVIDIA CORPORATION.  All rights reserved.
//
// NVIDIA CORPORATION and its licensors retain all intellectual property
// and proprietary rights in and to this software, related documentation
// and any modifications thereto.  Any use, reproduction, disclosure or
// distribution of this software and related documentation without an express
// license agreement from NVIDIA CORPORATION is strictly prohibited.

#include "../../framework_hip.h"
#include "../../hipraster/impl/Buffer.hpp"

using namespace CR;

//------------------------------------------------------------------------
// GPU buffer.
//------------------------------------------------------------------------

Buffer::Buffer(void)
:   m_gpuPtr(NULL),
    m_bytes (0)
{
    // empty
}

Buffer::~Buffer(void)
{
    if (m_gpuPtr)
        hipFree(m_gpuPtr); // Don't throw an exception.
}

void Buffer::reset(size_t bytes)
{
    if (bytes == m_bytes)
        return;

    if (m_gpuPtr)
    {
        NVDR_CHECK_CUDA_ERROR(hipFree(m_gpuPtr));
        m_gpuPtr = NULL;
    }

    if (bytes > 0)
        NVDR_CHECK_CUDA_ERROR(hipMalloc(&m_gpuPtr, bytes));

    m_bytes = bytes;
}

void Buffer::grow(size_t bytes)
{
    if (bytes > m_bytes)
        reset(bytes);
}

//------------------------------------------------------------------------
// Host buffer with page-locked memory.
//------------------------------------------------------------------------

HostBuffer::HostBuffer(void)
:   m_hostPtr(NULL),
    m_bytes  (0)
{
    // empty
}

HostBuffer::~HostBuffer(void)
{
    if (m_hostPtr)
        hipHostFree(m_hostPtr); // Don't throw an exception.
}

void HostBuffer::reset(size_t bytes)
{
    if (bytes == m_bytes)
        return;

    if (m_hostPtr)
    {
        NVDR_CHECK_CUDA_ERROR(hipHostFree(m_hostPtr));
        m_hostPtr = NULL;
    }

    if (bytes > 0)
        NVDR_CHECK_CUDA_ERROR(hipHostMalloc(&m_hostPtr, bytes));

    m_bytes = bytes;
}

void HostBuffer::grow(size_t bytes)
{
    if (bytes > m_bytes)
        reset(bytes);
}

//------------------------------------------------------------------------
